[project]
name = "task-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PavelPereverzev1", email = "pereverzev.pavel1975@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=5.2,<5.3",
    "django-allauth>=65.19.2",
    "django-environ>=0.14.0",
    "django-htmx>=1.29.0",
    "gunicorn>=26.2.0",
    "pre-commit>=4.6.2",
    "psycopg-pool>=3.3.1",
    "psycopg2-binary>=2.9.12",
    "ruff>=0.16.5",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "djhtml>=3.0.11",
]

